Repository croct-tech/coding-standard-js, pull requests merged in 2022-05, with the labels that each got.

#169 Change maximum line length to 120
  src/configs/javascript.ts
Labels: maintenance

#170 Fix padding-line to break before continue
  src/configs/javascript.ts
Labels: bug

#181 Disable react/destructuring-assignment rule
  src/configs/react.ts
Labels: enhancement
