Repository croct-tech/coding-standard-js, pull requests merged in 2022-02, with the labels that each got.

#1 Initial setup for Croct's ESLint
  .eslintrc.json
  .github/workflows/branch-validations.yaml
  .github/workflows/deploy-published-releases.yaml
  LICENSE
  README.md
  docs/README.md
  docs/rules/argument-spacing.md
  docs/rules/complex-expression-spacing.md
  docs/rules/jsx-attribute-spacing.md
  jest.config.js
  package-lock.json
  package.json
  src/.gitkeep
  src/configs/cypress.ts
  src/configs/index.ts
  src/configs/javascript.ts
  src/configs/react.ts
  src/configs/typescript.ts
  src/index.ts
  src/rules/argument-spacing/index.test.ts
  src/rules/argument-spacing/index.ts
  src/rules/complex-expression-spacing/index.test.ts
  src/rules/complex-expression-spacing/index.ts
  src/rules/createRule.ts
  src/rules/index.ts
  src/rules/jsx-attribute-spacing/index.test.ts
  src/rules/jsx-attribute-spacing/index.ts
  test/.gitkeep
  tsconfig.build.json
  tsconfig.json
Labels: documentation, feature

#3 Add test for boolean attributes
  src/rules/jsx-attribute-spacing/index.test.ts
Labels: maintenance

#4 Add NPM badge
  README.md
Labels: documentation

#5 Add CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#13 Change license to MIT and add author
  package.json
Labels: maintenance

#14 Add support for JS files on TS projects
  .eslintrc.json
  docs/README.md
  src/configs/typescript.ts
Labels: enhancement

#15 Update rule max-len to 100 characters
  src/configs/javascript.ts
Labels: bug

#16 Update JavaScript rules
  src/configs/javascript.ts
Labels: bug

#19 Disable linter `prefer-regex-exec`
  src/configs/typescript.ts
Labels: enhancement

#22 Remove rule @typescript-eslint/prefer-regexp-exec
  src/configs/typescript.ts
Labels: maintenance
