Repository croct-tech/coding-standard-js, pull requests merged in 2022-03, with the labels that each got.

#78 Fix max-len rule to not ignore strings
  src/configs/javascript.ts
  src/rules/argument-spacing/index.ts
  src/rules/complex-expression-spacing/index.ts
  src/rules/jsx-attribute-spacing/index.ts
Labels: bug

#25 Add rule newline-per-chained-call
  docs/README.md
  docs/rules/newline-per-chained-call.md
  src/configs/javascript.ts
  src/rules/index.ts
  src/rules/newline-per-chained-call/index.test.ts
  src/rules/newline-per-chained-call/index.ts
Labels: enhancement

#76 Add argsIgnorePattern to unused-vars
  src/configs/javascript.ts
  src/configs/typescript.ts
Labels: bug

#80 Fix newline-per-chained-call line break
  docs/rules/newline-per-chained-call.md
  src/rules/newline-per-chained-call/index.test.ts
  src/rules/newline-per-chained-call/index.ts
Labels: bug

#82 Fix newline-per-chained-call
  src/rules/newline-per-chained-call/index.test.ts
  src/rules/newline-per-chained-call/index.ts
Labels: bug

#83 Add min-chained-call-depth rule
  docs/README.md
  docs/rules/min-chained-call-depth.md
  src/configs/javascript.ts
  src/rules/index.ts
  src/rules/min-chained-call-depth/index.test.ts
  src/rules/min-chained-call-depth/index.ts
  src/rules/newline-per-chained-call/index.ts
Labels: feature

#86 Fix chained-call rules
  src/rules/min-chained-call-depth/index.test.ts
  src/rules/min-chained-call-depth/index.ts
  src/rules/newline-per-chained-call/index.test.ts
  src/rules/newline-per-chained-call/index.ts
Labels: bug

#87 Add sort-keys rule to react styles
  package-lock.json
  package.json
  src/configs/react.ts
Labels: enhancement

#89 Disallow useless escape characters
  src/configs/javascript.ts
Labels: enhancement

#94 Add eslint-comments plugin
  package-lock.json
  package.json
  src/configs/javascript.ts
  src/rules/argument-spacing/index.test.ts
  src/rules/argument-spacing/index.ts
  src/rules/complex-expression-spacing/index.test.ts
  src/rules/complex-expression-spacing/index.ts
  src/rules/jsx-attribute-spacing/index.test.ts
  src/rules/jsx-attribute-spacing/index.ts
  src/rules/min-chained-call-depth/index.test.ts
  src/rules/min-chained-call-depth/index.ts
  src/rules/newline-per-chained-call/index.test.ts
  src/rules/newline-per-chained-call/index.ts
Labels: feature

#93 Allow typescript namespaces
  src/configs/typescript.ts
Labels: enhancement, feature

#97 Prevent noisy destructuring on function parameter
  docs/rules/parameter-destructuring.md
  src/configs/javascript.ts
  src/rules/index.ts
  src/rules/parameter-destructuring/index.test.ts
  src/rules/parameter-destructuring/index.ts
Labels: feature

#95 Add rule for proper multiline destructuring
  package-lock.json
  package.json
  src/configs/javascript.ts
Labels: feature

#108 Increase newline-destructuring/newline items values
  src/configs/javascript.ts
Labels: bug

#107 Disable import/export rule for Typescript
  src/configs/typescript.ts
Labels: bug

#106 Add jsx-quotes rule to React config
  src/configs/react.ts
Labels: feature

#122 Fix security-checks
  package-lock.json
Labels: maintenance

#123 Remove sort-keys-fix plugin
  package-lock.json
  package.json
  src/configs/react.ts
Labels: maintenance

#133 Disable no-redeclare rule
  src/configs/typescript.ts
Labels: maintenance

#130 Fix min-chained-call-depth rule
  src/rules/min-chained-call-depth/index.test.ts
  src/rules/min-chained-call-depth/index.ts
Labels: bug

#134 Fix min-chained-call-depth rule
  docs/rules/min-chained-call-depth.md
  docs/rules/newline-per-chained-call.md
  src/rules/min-chained-call-depth/index.test.ts
  src/rules/min-chained-call-depth/index.ts
  src/rules/newline-per-chained-call/index.test.ts
  src/rules/newline-per-chained-call/index.ts
Labels: bug
